version: '2'
services:
    ui-app:
        image: ui
        external_links:
            - ui-mysql:mysql
            # Uncomment to have Cassandra working with the gateway
            # - ui-cassandra:cassandra
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    ui-mysql:
        extends:
            file: mysql.yml
            service: ui-mysql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: ui-cassandra
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
