version: '2'
services:
    api-mysql:
        container_name: api-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/api/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=api
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
